// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNHvsBN12nhFWTabBOBlk4SgWz8JY9PqM',
    appId: '1:825514846767:web:79c8cb2c49200439d0b4da',
    messagingSenderId: '825514846767',
    projectId: 'codehiveapp',
    authDomain: 'codehiveapp.firebaseapp.com',
    storageBucket: 'codehiveapp.appspot.com',
    measurementId: 'G-FZD9HYZXEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qMyfaPGnuzH_myLQ0l1_ahpRvNRCeus',
    appId: '1:825514846767:android:ebf9dc6a73d5f7aad0b4da',
    messagingSenderId: '825514846767',
    projectId: 'codehiveapp',
    storageBucket: 'codehiveapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pHeebjt6WIz8Sa_NvxsuuiZS5lFgQ-I',
    appId: '1:825514846767:ios:95744d27362c34a0d0b4da',
    messagingSenderId: '825514846767',
    projectId: 'codehiveapp',
    storageBucket: 'codehiveapp.appspot.com',
    iosClientId: '825514846767-sed5b9bh7hs0el74s89npnbfvbkkd9bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.codehive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9pHeebjt6WIz8Sa_NvxsuuiZS5lFgQ-I',
    appId: '1:825514846767:ios:95744d27362c34a0d0b4da',
    messagingSenderId: '825514846767',
    projectId: 'codehiveapp',
    storageBucket: 'codehiveapp.appspot.com',
    iosClientId: '825514846767-sed5b9bh7hs0el74s89npnbfvbkkd9bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.codehive',
  );
}
